# Семинар 2. Погружаемся в нейроны

### 0. С чего вообще все пошло?

![нейрон](https://psyfactor.org/neuropsy/i/xneuron2.jpg.pagespeed.ic.QWX_NDvFYO.webp)

Из строения нейрона делаем выводы:
- **Дендритов** (входных каналов) может быть **много**
- **Аксон** (выходной канал) может быть только **один** (но в будущем он может ветвиться)

У дендритов есть шипики, и чем больше шипиков, тем больше вклад (**вес**) конкретного дендрита в проводимость сигнала.  
Например: смотря на кошку, больший вклад в распознавание кошки вносят сигналы, получаемые зрительным нервом, нежели ощущения в пятке.

---

Теперь перенесемся к искусственным нейронам, имеем:
- Дендриты (входы)
- Аксон (выход)
- Тело нейрона 

![](https://wiki.loginom.ru/images/artificial-neuron.svg)

Внутри нейрона происходит суммирование всех сигналов с их весами:
$$
S = \sum_{i=1}^{n}{X_i \cdot w_i}
$$

**НО**  
Не все сигналы проходят дальше, иначе от нейронов не было смысла.  
На примере с кошкой представьте, что если бы у вас были закрыты глаза, а вы бы все равно распознавали образ кошки только потому что получаете сигналы от ощущений своей пятки.  
Поэтому нейрону необходимо еще **активироваться**, иначе говоря пропустить сигнал дальше при каких-то условиях, в простейшем случае - пороговая функция, как на рисунке ниже. 

![](https://aisimple.ru/uploads/posts/2020-04/1586743155_step.png)

Теперь перенесем имеющуюся информациию на язык Python.  
Инициализируем наши сигналы и веса.

In [2]:
x1 = 0.1
x2 = 0.3
x3 = 0.4
w1 = 0.2
w2 = -0.3
w3 = -0.1

Суммируем все это

In [3]:
s = x1 * w1 + x2 * w2 + x3 * w3
print(s)

-0.11


In [4]:
if s > 0:
    output_signal = 1
else:
    output_signal = 0
print(output_signal)

0


Нейрон не активировался, потому что суммарный сигнал оказался слишком слабым, чтобы пробить порог функции.  

Какие проблемы у кода выше? 
- Если много входов, то выражение для `s` станет невероятно большим, все придется писать руками.  
- Если хотим менять функцию активации, лучше обернуть ее в функцию Python.  

Можно ли сделать код еще лучше? Можно!

In [5]:
x = [0.1, 0.3, 0.4]
w = [0.2, -0.3, -0.1]


def sum_inside_neuron(x_list, w_list):
    output = 0
    for i in range(len(x_list)):
        output += x_list[i] * w_list[i]
    return output


def activation(input_signal):
    if input_signal > 0:
        return 1
    return 0

Проверяем

In [6]:
neuron_sum = sum_inside_neuron(x, w)
print(neuron_sum)

-0.11


In [7]:
print(activation(neuron_sum))

0


Теперь можем работать со сколь угодно большими по размерам `X` и `W`.

In [8]:
import random

In [13]:
random.random()  # возращает случайное число от 0 до 1

0.04002811292680519

In [18]:
x = [random.random() for _ in range(10000)]
w = [random.random() for _ in range(10000)]

neuron_sum = sum_inside_neuron(x, w)
print(neuron_sum)

print(activation(neuron_sum))

2471.938113976274
1


Хорошо, теперь умеем считать выход нашего нейрона для одного наблюдения за раз.  
А если хотим много наблюдений за раз?  
Что значит __много наблюдений__?  
Например, нейрон решает, пойду ли я гулять на основе 3 факторов:
1. Температура на улице
2. Скорость ветра
3. Есть ли у меня настроение гулять

Первые два признака называются __численными/непрерывными__, то есть могут принять любое число. Примеры: все, что можно посчитать и сравнить между собой, _температура_, _деньги_, _скорости_, _расстояния_, _возраст_ и т.д.   
Третий признак является __качественным/категориальным__, то есть может быть. Примеры: все, что нельзя сравнить между собой, и что является качеством объекта, _цвета_, _день недели_, _образование_, _гражданство_, _номер группы студента_.  

Допустим, вчера в 15:00 было -12 градусов на улице, скорость ветра 5 м/c, и у меня не было настроения (0).  
Тогда

In [19]:
x = [-12, 5, 0]
w = [random.random() for _ in range(3)]  # зададим случайные веса

neuron_sum = sum_inside_neuron(x, w)
print(neuron_sum)
print(activation(neuron_sum))

-4.4251595596643245
0


Затем, вчера же в 16:00 было -10 градусов, скорость ветра 1 м/c, и у меня есть настроение (1)

In [20]:
x = [-10, 1, 1]
# веса мы не обновляем, нейрон же остался прежним

neuron_sum = sum_inside_neuron(x, w)
print(neuron_sum)
print(activation(neuron_sum))

-6.12536283470414
0


Аналогично я могу собрать данные за все дни года, но неужели придется перепрогонять для каждого x эту ячейку снова и снова?  
**НЕТ**  
Мы умеем писать функции с необходимым функционалом

In [25]:
x_15_00 = [-12, 5, 0]
x_16_00 = [-10, 1, 1]
x_17_00 = [3, 0, 1]
x_18_00 = [5, 3, 0]

x_total = [x_15_00, x_16_00, x_17_00, x_18_00]
print(x_total)

[[-12, 5, 0], [-10, 1, 1], [3, 0, 1], [5, 3, 0]]


Обновляем функции, чтобы они умели работать с листами листов  
Варианта 2:
1. Переписать изначальную функцию  
2. Использовать первоначальную функцию для каждого листа

1 вариант

In [30]:
def sum_inside_neuron(x_list, w_list):
    output = []
    for x_one_list in x_list:
        total_sum = 0
        for i in range(len(x_one_list)):
            total_sum += x_one_list[i] * w_list[i]
        output.append(total_sum)
    return output


def activation(input_signal):
    output = []
    for one_signal in input_signal:
        if one_signal > 0:
            output.append(1)
        else:
            output.append(0)
    return output

In [27]:
sums = sum_inside_neuron(x_total, w)
print(sums)

[-4.4251595596643245, -6.12536283470414, 2.2374637791778915, 5.9514226947466735]


In [28]:
print(activation(sums))

[0, 0, 1, 1]


2 вариант

In [36]:
def sum_inside_neuron(x_list, w_list):
    """Умеет считать сумму для одного наблюдения"""
    output = 0
    for i in range(len(x_list)):
        output += x_list[i] * w_list[i]
    return output


def activation(input_signal):
    """Умеет считать активацию для одного наблюдения"""
    if input_signal > 0:
        return 1
    return 0


def total_sum_inside_neuron(x_list, w_list):
    """Умеет считать сумму для любого количества наблюдений"""
    output = []
    for x_one_list in x_list:
        one_output = sum_inside_neuron(x_one_list, w_list)
        output.append(one_output)
    return output


def total_activation(input_signal):
    """Умеет считать активации для любого количества наблюдений"""
    output = []
    for one_signal in input_signal:
        one_output = activation(one_signal)
        output.append(one_output)
    return output

In [37]:
sums = total_sum_inside_neuron(x_total, w)
print(sums)

[-4.4251595596643245, -6.12536283470414, 2.2374637791778915, 5.9514226947466735]


In [38]:
print(total_activation(sums))

[0, 0, 1, 1]


А насколько это быстро считается?

In [41]:
x_total = [[random.random() for _ in range(3)] for _ in range(5_000_000)]

In [49]:
%%time
sums = total_sum_inside_neuron(x_total, w)

Wall time: 4.32 s


In [50]:
%%time
activations = total_activation(sums)

Wall time: 1.13 s


Можно ли быстрее?  
**МОЖНО**

In [43]:
import numpy as np

In [44]:
x_total_np = np.array(x_total)
w_np = np.array(w)

In [59]:
%%time
output = x_total_np @ w_np  # через @ обозначается скалярное произведение векторов/матриц

Wall time: 10.3 ms


In [102]:
%%time
activation_vectorized = np.vectorize(activation)
activations_np = activation_vectorized(output)

Wall time: 1.05 s


In [101]:
activations[:10]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [100]:
activations_np[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [54]:
sums[:5]

[0.49487427043930055,
 0.6906733904411232,
 0.7780293098418298,
 0.9018110545190832,
 0.8818343082168674]

In [55]:
output[:5]

array([0.49487427, 0.69067339, 0.77802931, 0.90181105, 0.88183431])

4.32 секунды VS 10.3 миллисекунды

In [61]:
profit = 4.32 * 1e3 / 10.3
print("Быстрее в", round(profit), "раз!")

Быстрее в 419 раз!


# Библиотеки

**NumPy** (https://numpy.org) -- библиотека для работы с массивами.  
Работаем с примерами отсюда https://numpy.org/doc/stable/user/quickstart.html#the-basics

In [62]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
a.shape

(15,)

In [64]:
type(a)

numpy.ndarray

In [65]:
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
a.shape

(3, 5)

In [67]:
a.dtype

dtype('int32')

In [68]:
type(a)

numpy.ndarray

In [69]:
b = [2, 3, 4]
a = np.array(b)
a

array([2, 3, 4])

In [70]:
a.dtype

dtype('int32')

In [71]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [72]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [73]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [75]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [76]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

Операции с массивами

In [77]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [78]:
c = a - b
c

array([20, 29, 38, 47])

In [79]:
b ** 2

array([0, 1, 4, 9], dtype=int32)

In [80]:
b * 10

array([ 0, 10, 20, 30])

In [81]:
[0, 1, 2, 3] * 10

[0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3,
 0,
 1,
 2,
 3]

In [82]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [83]:
a < 35

array([ True,  True, False, False])

In [85]:
a

array([20, 30, 40, 50])

In [86]:
a[a < 35]

array([20, 30])

In [89]:
a = np.arange(12).reshape(6, 2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [91]:
a.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [94]:
a.shape

(6, 2)

In [95]:
a.T.shape

(2, 6)

In [92]:
a @ a.T

array([[  1,   3,   5,   7,   9,  11],
       [  3,  13,  23,  33,  43,  53],
       [  5,  23,  41,  59,  77,  95],
       [  7,  33,  59,  85, 111, 137],
       [  9,  43,  77, 111, 145, 179],
       [ 11,  53,  95, 137, 179, 221]])

In [96]:
(a @ a.T).shape

(6, 6)

In [93]:
a.T @ a

array([[220, 250],
       [250, 286]])

In [97]:
(a.T @ a).shape

(2, 2)

## Хорошо, но в реальных нейронных сетях не один нейрон, как быть в этом случае?
Вот нейронная сеть чуть посложнее, чем 1 нейрон  
![](https://robocraft.ru/files/neuronet/backpropagation/img01.gif)

Анализируем:
- Имеет два входа
- Потом 3 нейрона
- Потом еще 2
- И потом еще 1

Сгенерируем выборку

In [103]:
x_total = np.random.random(size=(10000, 2))

In [105]:
x_total[:5]

array([[0.09092732, 0.83709895],
       [0.11123983, 0.67039113],
       [0.19528601, 0.22168402],
       [0.28053582, 0.99927657],
       [0.48313133, 0.25541097]])

In [106]:
x_total.shape

(10000, 2)

Теперь разберемся с весами:    
У нас 3 нейрона, на каждый из них поступает сигнал с 2 входов.  
В прошлом примере у нас был 1 нейрон с 3 входами, и мы делали `w = [random.random() for _ in range(3)]`  
Теперь нейрон имеет 2 входа, значит `w = [random.random() for _ in range(2)]`

In [107]:
w_1 = [random.random() for _ in range(2)]

Но таких нейронов 3 штуки, значит, нужно 3 таких листа

In [116]:
w_1 = [random.random() for _ in range(2)]
w_2 = [random.random() for _ in range(2)]
w_3 = [random.random() for _ in range(2)]

Объединим их в один лист

In [117]:
w = [w_1, w_2, w_3]

In [119]:
w

[[0.6472460473055918, 0.7295033337840976],
 [0.3568658001551336, 0.05674864289326553],
 [0.8240869983410362, 0.5276935576044864]]

In [120]:
w = np.array(w)
w.shape

(3, 2)

То есть матрица весов будет размером (__количество нейронов в слое__, __количество входных нейронов__)

Если у нас будет 7 нейронов в слое с 3 выходами, то

In [121]:
w = np.random.random(size=(7, 3))

In [122]:
w

array([[0.50366207, 0.60833504, 0.6216208 ],
       [0.18478603, 0.36086179, 0.13829377],
       [0.5895319 , 0.92614545, 0.3472564 ],
       [0.54072621, 0.58328705, 0.36175768],
       [0.32456583, 0.60779459, 0.16479566],
       [0.26307051, 0.23613694, 0.05527608],
       [0.42252087, 0.496243  , 0.06553577]])

In [124]:
w.shape

(7, 3)

#### Вернемся к нашей изначальной нейросети с 3 нейронами в первом слое и 2 входами

In [126]:
w = np.random.random(size=(3, 2))
w

array([[0.14379419, 0.47308802],
       [0.30150614, 0.31753439],
       [0.58183388, 0.52190166]])

У нас есть X, у нас есть W, давайте их женить

In [129]:
x_total.shape

(10000, 2)

In [130]:
w.shape

(3, 2)

Если имеем 10000 наблюдений, то после прохода через 3 нейрона у нас должна быть матрица (10000, 3).  
Имеем матрицы (10000, 2) и (3, 2), как сделать (10000, 3)?

In [131]:
output = x_total @ w.T

In [132]:
output[:5]

array([[0.4090963 , 0.29322285, 0.48978793],
       [0.33314965, 0.24641173, 0.41460135],
       [0.13295705, 0.12927223, 0.22932128],
       [0.51308519, 0.40188795, 0.68474935],
       [0.19030335, 0.22676883, 0.41440158]])

In [133]:
output.shape

(10000, 3)

#### Дальше имеем 2 нейрона, где каждый получает сигнал от 3 сзадистоящих.  
Значит

In [134]:
w2 = np.random.random(size=(2, 3))

Как посчитать значения на нейронах дальше?  
Опять умножением

In [135]:
output.shape

(10000, 3)

In [136]:
w2.shape

(2, 3)

Из (10000, 3) и (2, 3) должны получить (10000, 2).

In [137]:
output_2 = output @ w2.T

In [138]:
output_2[:10]

array([[0.55849295, 0.95014173],
       [0.46375694, 0.79441937],
       [0.2213727 , 0.40089042],
       [0.74050174, 1.2841754 ],
       [0.36582636, 0.68694208],
       [0.81228614, 1.49787947],
       [0.68800015, 1.29411134],
       [0.56017529, 1.04589961],
       [0.63205011, 1.20866916],
       [0.40056968, 0.71760888]])

In [139]:
output_2.shape

(10000, 2)

#### В самом конце у нас один нейрон, значит

In [140]:
w3 = np.random.random(size=(1, 2))
output_3 = output_2 @ w3.T

In [141]:
output_3[:10]

array([[0.79364923],
       [0.66304034],
       [0.33247939],
       [1.07027252],
       [0.56746222],
       [1.23979095],
       [1.06883114],
       [0.86451861],
       [0.99650545],
       [0.59586921]])

In [142]:
output_3.shape

(10000, 1)

Бинго, мы получили 1 чиселко для каждого из 10000 наблюдений в выборке.

![](http://memesmix.net/media/created/l7sksl.jpg)

## Это здорово, но как сети учатся?  
Это мы узнаем на следующем семинаре